### PR TITLE
Modify Cronofy.php

### PR DESCRIPTION
**Pull request by qmeister**
I would like to propose to use protected instead of private so that the Cronofy objects can be inherited and it's functionality can be used by the child class. I need this to store all access token data (including expires_at) in a access token object to store this in the database next to my application's user account data. But in general using protected makes it more flexible to use.

### CODE REVIEW

**Comment by stephenbinns** [comment]
I'd rather we didn't expose the internals of the library in this way as it limits the refactoring we can do without causing breaking changes.

For your specific use case it probably makes sense we simply expose the `expires_at` attribute on the Cronofy class, I'm not sure how these changes would help with that?

**Comment by qmeister** [comment]
Fair enough. This would help also, and is enough for me to create a generic function in my inherited Cronofy class, which does the following:

1. check if token is expired based on expires_in param. If so: call refresh token and restore token data with user
2. call api function
3. check response for 401 (inherited handle_response). If unauthorized, refresh token, restore token with user and recall api function

Ps. I added another pull request in Adam's fork to add expires_in param in constructor also. 

If Adam's branch (add-expiry-to-token) could be merged it would be of great help.

Thanks for your support,
Jochem

**Comment by stephenbinns** [comment]
Right I think I understand more what you're trying to do - I will get the expiry branch merged.

I'm thinking a nice way to achieve what you're after would be for us to allow you to hook into the 401 call - perhaps passing an object into the class to handle the error. I will discuss with the other developers and see if we can come up with something

**Comment by qmeister** [comment]
Ok, thank you for your reply.

Currently I've got a subclass which overrides the handle_response function and checks for 401 before calling the parent, like this:

`
public function handle_response($result, $status_code)
    {
        if ($status_code == 401) {
            return false;
        }

        return parent::handle_response($result, $status_code);
    }
`

And this is the call function with the pre (isexpired) and post (401) check:
`public function call($function, $params)
    {
        if ($cronofyToken->isExpired()) {
            $this->refreshToken;
        }

        if (method_exists($this, $function)) {
            $result = $this->$function($params);

            if (!$result) {
                $this->updateUserToken();

                return $this->$function($params);
            }
        }

        return $result;
    }
`

**Comment by stephenbinns** [comment]
The `call` function you have is making the API call twice I think you want something like:

```php
    public function call($function, $params = null)
    {
            $result = false;

            if ($cronofyToken->isExpired()) {
                    $this->refreshToken();
            }

            if (method_exists($this, $function)) {
                    $result = $this->$function($params);

                    if (!$result) {
                            if ($this->refreshToken()) {
                                     $result = $this-$function($params);
                            } else {
                                     // TODO: Some error to indicate refresh failed
                            }
                    }
            }

            return $result;
    }
```

**Comment by qmeister** [comment]
You're totally right. This code is a bit messy. While adding this comment I modified it, and I forgot to update the comment with my latest changes. 
Anyhow I hope you get the general idea what I'm trying to do, and why. Thank you for your feedback anyways.

**Pull request closed without merging**
