### PR TITLE
Madewithlove add list accessible calendars

### PR DESCRIPTION
**Pull request by tomhazledine**

### CODE REVIEW

**Comment by mkarnicki** [comment]
It seems the v0.26 build failed in Travis?

**Comment by tomhazledine** [comment]
@mkarnicki it was a GIT issue on the PR - the main build passed: https://travis-ci.org/cronofy/cronofy-php/builds/598218902

**Comment by mkarnicki** [comment]
I see. Should we see v0.26.0 in packagist?

**Comment by tomhazledine** [comment]
Hmmm, you're right: it's not appearing in packagist. Turns out something's gone awry with the tagging/release task... I'm looking into this now, and will report back as soon as it's fixed.

**Comment by tomhazledine** [comment]
@mkarnicki The release has been made successfully now, so v0.26.0 is available in packagist 👍

**Comment by mkarnicki** [comment]
@tomhazledine Yay, thank you so much Tom!

**Pull request merged**
