### PR TITLE
Add method bulkDeleteEvents

### PR DESCRIPTION
**Pull request by kgrab75**

### CODE REVIEW

**Comment by kr-mykyta** [comment]
Hi Kevin,

Thank you for submitting this PR! We will review, test, and let you know once this is merged.

Best,
Mykyta.

**Comment by kgrab75** [comment]
> Hi Kevin,
> 
> Thank you for submitting this PR! We will review, test, and let you know once this is merged.
> 
> Best, Mykyta.

Thanks @kr-mykyta :) 
Have you an ETA?

**Comment by kr-mykyta** [comment]
@kgrab75 this should be approved this week, I am finalizing my changes to the PR and having it reviewed, so it should be fairly quick now.

**Comment by kr-mykyta** [comment]
@kgrab75 just wanted to give you a quick update that this is almost done, I need to make a couple of changes to a test I've written for this to make sure that this would work as expected in Production, so there is a slight delay and I will get it released Monday.

Apologies for the delay!

**Comment by kgrab75** [comment]
@kr-mykyta that's good for me 🙂
Thanks for your work 🙏

**Comment by kr-mykyta** [comment]
Hi Kevin,

Apologies for the delay, this has now been merged!

Thanks a lot for your contribution!

Best,
Mykyta.

**Pull request merged**
