### PR TITLE
Added the ability to send event_classes for an event request

### PR DESCRIPTION
**Pull request by andrewapplicantpro**

### CODE REVIEW

**Comment by AdamWhittingham** [comment]
Thank you, @andrewapplicantpro!
We'll get this tested, merged and released 👍

**Comment by kr-mykyta** [comment]
Hi @andrewapplicantpro, we have now merged this with PR #125 and released it under the version 1.7.0

Thank you very much!

**Comment by andrewapplicantpro** [comment]
Thank you!

**Comment by andrewapplicantpro** [comment]
I did notice you updated composer.json to 1.7. Will the git tag version also get updated to 1.7 so this can be used with composer on our end, or is that done automatically on a schedule?

**Pull request closed without merging**
